Bugfix openvdb unittest
Error :
TestStreamCompression.cc(464): Error C2664 : 'boost::winapi::DWORD_ GetTempPathW(boost::winapi::DWORD_,boost::winapi::LPWSTR_)': cannot convert argument 2 from 'char [261]' to 'boost::winapi::LPWSTR_'
TestStreamCompression.cc(464): Reference C2664 : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
directory_management.hpp(36): Reference C2664 : see declaration of 'GetTempPathW'
TestStreamCompression.cc(464): Reference C2664 : while trying to match the argument list '(int, char [261])'